### ISSUE TITLE
Colours not rendering for Markdown report generated by Dotnet Outdated

### ISSUE THREAD

**Issue by andrew-flatters-bliss** [masamitsu-murase/publish_markdown_reports#4]
Raised on the Dotnet global tool outdated GitHub repo also but looks like the syntax they are using for colours aren't working with this extension:

https://github.com/dotnet-outdated/dotnet-outdated/issues/340#issuecomment-1490236058

What it outputs:
<html>
<body>
<h3 id="targetnet60" style="margin: 0px 0px 8px; padding: 0.875rem 0px 2px; line-height: 1; color: var(--darkreader-text--nc-tx-1); border-bottom: 1px solid var(--darkreader-border--nc-bg-2); font-size: 1.55rem; font-family: Inter, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Open Sans&quot;, &quot;Helvetica Neue&quot;, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(0, 0, 0); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Target:net6.0</h3>

Package | Transitive | Current | Last | Severity
-- | -- | -- | -- | --
Microsoft.EntityFrameworkCore | False | 6.0.15 | $\textcolor{red}{\textsf{7.0.0}}$ | Major
Microsoft.EntityFrameworkCore.Cosmos | False | 6.0.15 | $\textcolor{red}{\textsf{7.0.0}}$ | Major

<br class="Apple-interchange-newline">
</body>
</html>

What DevOps renders:
![image](https://user-images.githubusercontent.com/63094835/228839914-c60636f0-7433-4b73-967f-55417532b72c.png)

**Comment by masamitsu-murase** [comment]
This feature, such as `$\textcolor{red}{xxx}$`, is now supported by v1.7.0.
Could you check it?

Regards,
Murase

**Comment by andrew-flatters-bliss** [comment]
![image](https://github.com/masamitsu-murase/publish_markdown_reports/assets/63094835/ce278653-d3ff-49ce-a9c7-62132572780b)
Working great :) Thanks!
