### ISSUE TITLE
Publishing a report from a folder is uploading the entire folder recursively 

### ISSUE THREAD

**Issue by michaelcodeshenanigans** [masamitsu-murase/publish_markdown_reports#6]
Hi,
We've started using the extension in our organization and noticed our Azure DevOps Server DB started to grow rapidly.

After investigating we've noticed that after the publish markdown report task completed the pipeline was still running and uploading the content of the folder as attachments to our DB.

The solution for now is publishing a report in a separate folder obviously but it also might be an easy fix if anyone wants to try.

**Comment by masamitsu-murase** [comment]
I'm sorry for my late reply.

Yes. It is currently intentional and I think that your solution is appropriate.
Because this extension can publish multiple markdown files and images, it uploads all files in the directory specified by `contentPath`.
